// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_I6gfamLdVa84B_YSNkGSkVpR2-qzWFY',
    appId: '1:1001779211048:web:5704ee6cccf55140e77e1d',
    messagingSenderId: '1001779211048',
    projectId: 'interesting-flutter',
    authDomain: 'interesting-flutter.firebaseapp.com',
    storageBucket: 'interesting-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAerTxkYJk8Gm_CJCZ5upLQjgd9DamEmzQ',
    appId: '1:1001779211048:android:860ef268c736fe48e77e1d',
    messagingSenderId: '1001779211048',
    projectId: 'interesting-flutter',
    storageBucket: 'interesting-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkdnbn2L5Z6F0r9ZjSVRBOJxvC1uxjk7U',
    appId: '1:1001779211048:ios:ec4e4dfaf3a948c3e77e1d',
    messagingSenderId: '1001779211048',
    projectId: 'interesting-flutter',
    storageBucket: 'interesting-flutter.firebasestorage.app',
    iosBundleId: 'com.example.interestingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkdnbn2L5Z6F0r9ZjSVRBOJxvC1uxjk7U',
    appId: '1:1001779211048:ios:ec4e4dfaf3a948c3e77e1d',
    messagingSenderId: '1001779211048',
    projectId: 'interesting-flutter',
    storageBucket: 'interesting-flutter.firebasestorage.app',
    iosBundleId: 'com.example.interestingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_I6gfamLdVa84B_YSNkGSkVpR2-qzWFY',
    appId: '1:1001779211048:web:18b3a9da636a3ea5e77e1d',
    messagingSenderId: '1001779211048',
    projectId: 'interesting-flutter',
    authDomain: 'interesting-flutter.firebaseapp.com',
    storageBucket: 'interesting-flutter.firebasestorage.app',
  );
}
